### ISSUE TITLE
an AttributeError occurs when I run ocr_train.py

### ISSUE THREAD

**Issue by Kevinnest** [gongxijun/ocr_recognition#1]
the error occurs like that:
```
kelvin@kelvin-VirtualBox:/work/ocr_recognition-master/recaptcha$ python ocr_train.py 
Traceback (most recent call last):
  File "ocr_train.py", line 196, in <module>
    num_label=arg.num_label)
  File "/work/ocr_recognition-master/recaptcha/lstm.py", line 84, in lstm_unroll
    sm = mx.sym.WarpCTC(data=pred, label=label, label_length=num_label, input_length=seq_len)
AttributeError: 'module' object has no attribute 'WarpCTC'
```
I have installed the warp-ctc and torch, and I can run the test_cpu under the warp-ctc/build/ succesfully
```
kelvin@kelvin-VirtualBox:/work/warp-ctc/build$ ./test_cpu 
Running CPU tests
Tests pass
```
Could you give me some suggestions to fix the error?

**Comment by gongxijun** [comment]
e..., did you bind warp-ctc to mxnet ? maybe you can try 
go to mxnet/make/config.mk
add some info like this :
167 WARPCTC_PATH =/home/gongxijun/warp-ctc
168 #$(HOME)/warp-ctc
169 MXNET_PLUGINS += plugin/warpctc/warpctc.mk

and then make mxnet  again !

**Comment by gongxijun** [comment]
@Kevinnest  it's　solved your problem ?
