### ISSUE TITLE
mxnet  version

### ISSUE THREAD

**Issue by Hjy20255** [gongxijun/ocr_recognition#2]
can you tell me your mxnet version？

**Comment by gongxijun** [comment]
Used in any version,but lastest version maybe work well.

**Comment by gongxijun** [comment]
@Hjy20255  

> Used in any version,but lastest version maybe work well

**Comment by Hjy20255** [comment]
@gongxijun 
i run predict.py
error: mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
my mxnet version:
import mxnet as mx
mx.__version__
'0.9.4'

**Comment by gongxijun** [comment]
@Hjy20255 
e , i think it just a warning,just like the resouce:

> logging.warning('\033[91m[Deprecation`

 Warning] mxnet.model.FeedForward has been 'Please use mxnet.mod.Module instead.\033[0m');

so you can ignore the info and go ahead  , or  maybe you  should use the version  0.9.1
