### ISSUE TITLE
请教一个问题，mxnet 0.10.0运行你的代码提示错误

### ISSUE THREAD

**Issue by flice** [gongxijun/ocr_recognition#3]
运行提示:
 src/operator/./slice_channel-inl.h:198: Check failed: ishape[real_axis] == static_cast<size_t>(param_.num_outputs) (3000 vs. 30) If squeeze axis is True, the size of the sliced axis must be the same as num_outputs. Input shape=(100,3000), axis=1, num_outputs=30.

我修改了您的源码中第64行   :     self.provide_data = [('data', (batch_size, image_width * image_height))] + init_states
为：     self.provide_data = [('data', (batch_size,  image_height,image_width))] + init_states
其中　img = img.reshape((image_width * image_height)) 　也reshape成二维
BATCH_SIZE 也修改成height值

可以运行，但是精度一直为０，迭代了１００次都这样。请问我是哪里忽略了或者设置错误了吗？

**Comment by gongxijun** [comment]
这个刚开始收敛比较慢，可以多迭代几次些试试，这个还不好明确的说是什么问题.

**Comment by gongxijun** [comment]
@flice 
这个刚开始收敛比较慢，可以多迭代几次些试试，这个还不好明确的说是什么问题.
